### ISSUE TITLE
(Suggestion) Make Potion of Bees work with Dispensers 

### ISSUE THREAD

**Issue by TelepathicGrunt** [Commoble/potionofbees#2]
Just an idea that's pretty easy to implement. You could make the Potion of Bees item be used up and spawn bees in front of the Dispenser when activated. And you could have the Bee Splash Potion be thrown by the Dispenser like other splash potion are.

You just need to make a class that extends extends DefaultDispenseItemBehavior and implements dispenseStack(IBlockSource source, ItemStack stack). Then you just need to call this method somewhere after the item is registered 
`DispenserBlock.registerDispenseBehavior(ForgeRegistries.ITEMS.getValue(ResourceLocations.POTION_OF_BEES), new BeePotionDispenseBehavior());`

Hope this helps!

**Comment by Commoble** [comment]
This is a good idea and I'll get around to it eventually
