### ISSUE TITLE
[Bug] Potion of Bees have no JEI recipe

### ISSUE THREAD

**Issue by drakray** [Commoble/potionofbees#5]
The recipe work, but JEI is not showing it

MC 1.16.3
Forge 34.1.19
PoB 1.1.0.0
JEI 7.6.0.49
Buncha others

**Comment by Commoble** [comment]
Fixed in [1.16.3-1.1.0.1](https://github.com/Commoble/potionofbees/commit/2af3ac5bc59f3777fe616954c5f0ed6b558817cf)
